### ISSUE TITLE
다시 시작하기(restart) 요청

### ISSUE THREAD

**Issue by lqez** [stackoverflow-in-korean/sok#1]
Area51 에 다시 시작하기(restart) 요청을 넣기

**Comment by aronze** [comment]
요청 넣는 법을 잘 모르겠어요. 아시는 분 좀 알려주세요~

**Comment by lqez** [comment]
restart 가 제안된 proposal을 다시 여는(open)게 아니라, 다시 제안을 넣는다는 의미로 보여, @aronze 님이 새로 proposal을 만들어 두었습니다.
http://area51.stackexchange.com/proposals/68765/stack-overflow-in-korean

나중에 이 링크를 통해 홍보하면 될 것 같습니다.
