### ISSUE TITLE
안녕하세요. 미친척하고

### ISSUE THREAD

**Issue by jinahya** [stackoverflow-in-korean/sok#10]
proposal 을 열어 버렸습니다. 혹시 공유 가능한 분 있으시면 부탁드립니다.

http://area51.stackexchange.com/proposals/95548/stackoverflow-in-korean

60명의 follower 와 40개의 질문이 필요하군요.

사전에 아무런 준비도 하지 않았습니다만, SNS 를 이용한 단기간의 파급력을 토대로 해 보려 합니다.

http://area51.stackexchange.com/proposals/95548/stackoverflow-in-korean

**Comment by jason-heo** [comment]
더 이상 Stackoverflow on OOO  같은 건 제안을 안받겠다는 글이 있습니다. ^^;

본인들이 정한 우선 순위에 맞춰서 순차적으로 오픈한다더군요.

**Comment by jinahya** [comment]
아.. 아니 그런....ㅜㅜ

**Comment by jason-heo** [comment]
제가 지금 누워있다보니 모바일로는 링크를 못찾겠네요. 

내일 걸어드릴게요. 저희 sok 채팅방에 링크 적었는데 채팅방 url도 몰라서요..

**Comment by jinahya** [comment]
@mysqlguru 감사합니다.

**Comment by coffeeshopcoder** [comment]
기존 [채팅방](http://chat.stackoverflow.com/rooms/56617/stackoverflow-in-korean) 액티비티가 없어 프로즌 상태로 전환됐네요. 링크를 공유할 다른 방법을 찾아봐야 할 것 같습니다.

**Comment by jinahya** [comment]
빠르네요.

Unfortunately, we are not currently accepting proposals for non-English sites — See Internationalization 'State of the Stack' – Robert Cartaino

**Comment by jason-heo** [comment]
채팅방은 [여기서](http://chat.stackexchange.com/rooms/15571/stackoverflow-in-korean) 유지 중입니다. ikh 님께서 프로즌 안 되게 열심히 활동 중이시죠.

**Comment by NunciosChums** [comment]
아...이제 제안을 안 받아서 삭제된 거군요 ㅠㅠ 다시 해보자고 말하려 했는데 안되겠네요 ㅠㅠ
