### ISSUE TITLE
SOK 페푹 페이지 운영에 대한 의견을 구합니다.

### ISSUE THREAD

**Issue by jason-heo** [stackoverflow-in-korean/sok#12]
[SOK 페북 페이지](https://www.facebook.com/kr.stackoverflow/)는 2014년 1차 오프미팅 의견으로 만들어진 페이지입니다. 취지는 사람들을 많이 모아서 SOK 활동 참여를 독려하기 위함이었습니다.

그런데 아시다시피 SOK 같은 다국어 사이트는 더이상 저희 의지로 개설될 수 없습니다. 그리고 페북 페이지 업데이트 또한 거의 없는 편이고요.

그래서 페북 페이지 운영을 계속할지 말지에 대해서 이야기를 해보는 것이 좋을 것 같습니다.

댓글로 의견 남겨주셔도 되고, 간단하게 투표를 해 주셔도 됩니다. (투표는 익명이라서 누가 어떤 항목을 선택했는지 볼 수 없습니다.) 
- https://docs.google.com/forms/d/1rIpu5XzFHXvrYZBuzBtPKWAA1qBtllo48tQxYp0qsGs/viewform

감사합니다.

**Comment by jwChung** [comment]
게시물을 작성하고 싶은 분은 작성하시면 어떨까하는 생각합니다. 굳이 close할 필요가 있을까하는 생각입니다. 보기에는 없지만 그냥 둔다 한 표 던집니다.

**Comment by jason-heo** [comment]
현재 페북 페이시의 상황은,
1. 업데이트가 거의 없다
2. 의도치 않게 잘못된 정보가 퍼지는 경우가 있다.

1번 업데이트 없는 건 아주 큰 문제는 아닌데, 2번의 경우 좀 문제가 된다고 생각합니다. 어제 올라온 글만해도 3만2천명에게 도달이 되었는데, 반응을 보면 사람들은 마치 SOK가 오픈된 것처럼 이해하는 듯 합니다. 의도한 바는 아니겠지만 결국 사이트 홍보가 된 것 아닌가 생각도 들고요.

그 전에 올라온 글도 8천명에게 도달되었는데 마치 좀 있으면 SOK가 오픈된다는 뉘앙스의 글이라서 긴급히 수정을 했었죠.

종합해보면 게시물 작성하는 사람도 없고, 의도치 않게 잘못된 내용이 전파되는 상황에서 원래 페이지 개설 목적인 SOK 개설 홍보에 대한 목적 자체가 불가능하니, 페이지를 종료하는 게 낫지 않나하는 생각이었습니다. 혹은 잠시 비공개로 했다가 SOK 오픈 즈음에 오픈 홍보를 위해 활동을 재개하는 것도 옵션 중의 하나고요.

이상은 저의 생각이었고요. 혼자 결정할 수 있는 문제는 아니다보니 같이 이야기해봤으면 하여 이슈 올려봤습니다.

감사합니다.

**Comment by BenjaminKim** [comment]
@mysqlguru 며칠전 그 포스팅은 올린 것은 저인데요, 저는 큰 문제가 아니라고 생각하는데 서로 생각하는 바가 다르다보니 오해가 생기고 있는 것 같습니다. ^^;
처음에 우리가 모였던 목적이 한국어로된 Q&A 게시판을 스택오버플로우를 통해 활성화시켜보자 였다고 기억을 합니다. 여러 사람들이 노력해주었지만 아쉽게도 불발되었었고, 다시 같은 방식으로 도전하기는 좀 무리인 것 같네요.
그러는 와중에 대안 사이트로써 꽤 괜찮은 사이트가 나와서 제가 홍보를 해줄겸 글을 올린 것이구요. 의도한바가 아니겠지만이라고 말씀해주셨는데 의도한바가 맞습니다. ^^; 저는 이런 사이트들을 돕는 것이 원래 우리가 하려고 했던 목적에 여전히 부합하다고 생각을 합니다.

서로 대화가 요원해지다보니 각자의 생각들을 잘 알수가 없어서 생긴 문제라는 판단이 듭니다. 미리 내용을 공유하고 설득한 뒤 일을 진행하면 더 좋았을텐데 그렇게 진행하지 않은 것은 제 잘못입니다. :cry:

**Comment by jwChung** [comment]
@mysqlguru 듣고 보니 정수님 의견에 공감이 가네요. 저는 close로 투표를 했습니다. :)

**Comment by jason-heo** [comment]
@BenjaminKim 님 아이디어로 페북 페이지 개설하게 되었는데 덕분에 그동안 많은 사람에게 저희 활동을 홍보할 수 있었습니다. 감사합니다.

우선 SOK 목적에 대해 서로 다르게 생각하는 것 같습니다 ^^; 채팅 회의에서 SOK 개설 실패한 경우 so-like한 서비스에 대한 이야기도 있었는데, 결론은 SOK에 집중하자로 이야기되었었습니다.

현재 상황에서 페북 페이지에 so의 재미있는 질문&답변 올리는 것도 한계가 있고, 그렇게 해서 좋아요를 많이 받아봤자 이제는 다국어 페이지 개설은 제안할 수도 없으니 페북 페이지의 존재가 무슨 의미일까 생각되었습니다.

Q&A 이외에 기타 소식들도 허용하면서 앞의 2개 게시물 같은 건을 방지하려면 마치 Pull Request처럼 게시물 올리기 원하는 사람이 요청하고 리뷰어가 승인하는 식으로 운영해야 하는데 이렇게까지 운영하긴 어려울 것 같습니다.

@aronze, @dlarudgus20, @emeth-kim, 노영선님 생각은 어떤지 궁금합니다.

현재 투표는 참여율이 저조해서 (4분 참여) 이걸 토대로 결정하긴 어렵네요.

**Comment by jason-heo** [comment]
2년전 페북 페이지 만들 땐 못봤던 건데, 공식 so 페이지가 있었네요...

https://www.facebook.com/officialstackoverflow/

**Comment by dlarudgus20** [comment]
저는 일단은 그대로 운영하는게 좋지 않을까 생각합니다. proposal을 받지 않는다고 해도, so에서 한국인의 활동이 많아야 stackexchange 측에서 개설을 검토할 수가 있겠죠. (저번에 다음 개설할 다국어 사이트 후보로 한국어를 들었던 적이 있으니..) 의미가 없다고는 생각하지 않아요.

저희 페북 페이지에 아무나 글을 올릴 수 있었던가요? pull req 이야기를 하시니 궁금해져서요.

**Comment by jason-heo** [comment]
@dlarudgus20 페이지 관리자로 등록된 사람만 아무나 올릴 수 있는데요. 관리자도 지난 두번 같은 일을 방지하려면, 어떤 관리자가 올린 글이 publish되기 전에 다른 관리자가 review를 하는 게 좋다는 것을, PR 같은 프로세스가 있어야 한다는 의미로 비유를 든 겁니다.

**Comment by aronze** [comment]
저는 유지하는게 좋다고 생각합니다. 이유는 이미 펜페이지가 상당히 커져서 파급력이 생겼기 때문입니다. 잘 못된 정보가 순식간에 퍼지는 문제도 있지만, 반대로 쉽게 많은 분들께 손쉽게 정보를 전달할 수 있는 채널이라는 뜻이기도 하니까요. 이런 채널을 그냥 버리는건 좀 아까운것 같아요.

다만, 오해의 소지가 있는 정보가 공유되는 것은 문제가 있다고 생각합니다. 글을 올리고 최소 몇 명 이상의 동의가 있어야 글을 게시 할 수 있도록 하는 방법이 좋다고 생각합니다. 이 부분은 타이트하게 강제하기 보다는, 자율적으로 커뮤니티의 검토를 부탁하고 좀 더 신중하게 올리는 정도만 제한해도 충분하다고 생각합니다. 

@BenjaminKim 이 올리신 글에 대한 의견인데요, 민감한 문제긴 하지만 상업적인 의도가 아니라면 커뮤니티에 의견을 구하고 올려도 좋다고 생각합니다.(어디까지나 제 개인적인 생각이에요. 다른 분들 의견을 들어보고 종합하는게 중요할 것 같네요.)

마지막으로, 페이스북 페이지를 유지한다면, 어떤 컨텐츠를 올릴것인지에 대한 고민을 커뮤니티 안에서 다시 했으면 좋겠습니다. 

추가: 
관리자 이외에도 SOK 펜 페이지를 사용하고 있는 다른 분들께 이 질문을 던저 보는 것은 어떨까요?

**Comment by jason-heo** [comment]
네. 그럼 page는 계속 유지하기로 하며 본 issue는 close하겠습니다.

참고로 투표 결과는 아래와 같습니다.

| 타임스탬프 | 운영을 계속 할까요? |
| --- | --- |
| 2016. 3. 16 오후 12:26:52 | 계속 운영한다 |
| 2016. 3. 16 오후 1:55:16 | 비공개로 전환 후, SOK 열릴 때 재오픈 |
| 2016. 3. 16 오후 10:07:21 | 비공개로 전환 후, SOK 열릴 때 재오픈 |
| 2016. 3. 17 오후 3:31:29 | Close한다 |
| 2016. 3. 18 오전 12:04:20 | 계속 운영한다 |
| 2016. 3. 18 오전 10:10:56 | 계속 운영한다 |
| 2016. 3. 18 오후 7:01:21 | 계속 운영한다 |
| 2016. 3. 22 오후 6:15:57 | 계속 운영한다 |
