### ISSUE TITLE
proposal이 삭제되었어요 ㅜㅜ

### ISSUE THREAD

**Issue by yevgnenll** [stackoverflow-in-korean/sok#13]
안녕하세요 멋진 프로젝트를 위해 수고 많으십니다

https://area51.stackexchange.com/proposals/68765/stack-overflow-in-korean

링크로 들어가보니 삭제되었다고 나옵니다 ㅜㅜㅜㅜㅜ

**Comment by outsideris** [comment]
이제 SO에서 언어별 제안을 받지 않는 것으로 알고 있습니다. #10 을 참고하세요.
