### ISSUE TITLE
Area51의 FAQ 번역

### ISSUE THREAD

**Issue by lqez** [stackoverflow-in-korean/sok#2]
http://area51.stackexchange.com/faq

**Comment by lqez** [comment]
https://github.com/so-in-korean/sok/wiki/What-is-Area-51%3F-%EB%B2%88%EC%97%AD
번역을 용이하기 진행하기 위해 wiki에 페이지로 만들었습니다.

**Comment by outsideris** [comment]
일단 러프하게 번역을 했습니다.
commit, commitment처럼 번역이 좀 어려운 단어들이 좀 있네요. ㅠㅠ

**Comment by lqez** [comment]
헐 정말 빠르게 작업하셨네요 !!! :+1:

**Comment by outsideris** [comment]
절반만 해서 올리려다가 하다보니.. 계속하게 됐네요. ㅎ 수정필요한 문장이 많습니다. ㅠㅠ

**Comment by lqez** [comment]
한글 링크가 불편하여 링크를 수정했습니다. 
https://github.com/so-in-korean/sok/wiki/What-is-Area-51%3F-(in-Korean)
